config/routes.rb
LogCleaner::Application.routes.draw do
  root :to => 'cleaners#main'
  resources :cleaners do
    collection do
      get 'main'
      post 'process_file'
      get 'download'
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cleaners_controller.rb
require 'tempfile'

class CleanersController < ApplicationController
	respond_to :js, :html

	CHECK_STRING = ['msg rcv', 'msg to send', 'EV.ERR']

	def main
	end

	def process_file
		logger.info params[:file].class
		new_filename = sanitize_filename(params[:file])
		logger.info "!!!!!!!!!!!!!!!!!!!!!"
		logger.info new_filename
		@content = params[:file].read
		logger.info "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
		# File.open "#{Rails.root}/tmp/#{new_filename}.txt", 'wb', :output_encoding => "binary" do |file|
		file = File.open("txlogs/#{new_filename}", "w+")
		file.binmode
		begin
			@content.each_line do |r|
				if  (r.include?('<#>') && include_string?(r, CHECK_STRING)) || ((r.include? '<#>') == false)
					# include_string?(r, CHECK_STRING )) || ((r.include? '<#>') == false)
					file.puts r
				end
			end
			file.close
			logger.info '#######################################'
			logger.info file.path
			@filepath = file.path
			@filename = new_filename
			respond_to do |format|
				format.js
			end
		end
	end

	def download
		logger.info params 
		logger.info "@@@@@@@@@@@@@@@@@@@@@@@@@@"
		send_file params[:filepath], :inline => false
	end

	private

	def sanitize_filename(file)
	
		stripped_file = (browser.ie? ? file.original_filename : file.original_filename)

		if stripped_file.include? '.txt'
			stripped_file.sub(".txt", "_cleaned.txt")
		else
			stripped_file.sub(".log", "_cleaned.txt")
		end
	end


	def include_string?(line, array)
		array.each do |string|
			if line.include? string
				return true
			end
		end
		return false
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	ALERT_TYPES = [:error, :info, :success, :warning]

	def bootstrap_flash
		flash_messages = []
		flash.each do |type, message|
       # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
       next if message.blank?

       type = :success if type == :notice
       type = :error   if type == :alert
       next unless ALERT_TYPES.include?(type)

       Array(message).each do |msg|
       	text = content_tag(:div,
       		content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
       		msg.html_safe, :class => "alert fade in alert-#{type}")
       	flash_messages << text if message
       end
   end
   flash_messages.join("\n").html_safe
end
end

app/helpers/cleaner_helper.rb
module CleanerHelper
end

app/views/cleaners/_download.html.erb
<%= link_to "Download #{@filename}", download_cleaners_path(:filepath => @filepath) %>

app/views/cleaners/main.html.erb


<%= form_tag process_file_cleaners_path, multipart: true, remote: true, id: 'upload-form' do %>
  <label for="file" class="upload-label">File to Upload</label>
  <%= file_field_tag :file, id: "upload-log" %>
  <br>
  <%= submit_tag( "Make my log awesome", :class => "btn btn-primary" ) %>
  <%= image_tag "ajax-loader.gif", :style=> "display:none", id: 'loader' %>
<% end %>
<br/>
<div id="download-container"></div>
<br/>

app/views/cleaners/process_file.js.erb
	// send_file , :x_sendfile => true

	$("#download-container").html("<%= escape_javascript( render(:partial => 'download')) %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Awesome Log Cleaner" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Awesome Log Cleaner</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%#= link_to "Link1", "/path1"  %></li>
              <li><%#= link_to "Link2", "/path2"  %></li>
              <li><%#= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Global Blue 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>